services:
  postgres:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 10
    networks:
      - app-network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    command: >
      --requirepass redissecret
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redissecret", "ping"]
      interval: 3s
      timeout: 10s
      retries: 10
    networks:
      - app-network

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    volumes:
      - ./api:/app/api
      - ./pipecat:/app/pipecat
    environment:
      ENVIRONMENT: local
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@postgres:5432/postgres
      REDIS_URL: redis://:redissecret@redis:6379
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: voice-audio
      MINIO_SECURE: "false"
      BACKEND_API_ENDPOINT: https://latesha-lineable-sharyn.ngrok-free.dev
      NGROK_API_URL: http://ngrok:4040/api/tunnels
      WAIT_FOR_PROCESSES: "true"
      LOG_TO_FILE: "false"
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      ngrok:
        condition: service_started
    networks:
      - app-network

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "http"
      - "--domain=latesha-lineable-sharyn.ngrok-free.dev"
      - "api:8000"
    environment:
      - NGROK_AUTHTOKEN=3AO35YbUNJn6bEoKRxHeifek1Tk_2xxXBbMwe81d5tF1ANGGk
    ports:
      - "4040:4040"
    networks:
      - app-network

volumes:
  postgres_data:
  redis_data:
  minio_data:

networks:
  app-network:
    driver: bridge
